### ISSUE TITLE
Panic over `libarchive_seek_callback` when using compress-tools with tokio

### ISSUE THREAD

**Issue by YaxinCheng** [OSSystems/compress-tools-rs#96]
I am trying to list content from this
[test.zip](https://github.com/OSSystems/compress-tools-rs/files/10330574/test.zip). However, it gives me error like this

```
internal error: entered unreachable code: We need to use libarchive_seek_callback() underlying.
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: We need to use libarchive_seek_callback() underlying.'
```

Here is my `Cargo.toml` and code

```toml
#Cargo.toml

[dependencies]
compress-tools = { version = "0.14", features = ["tokio_support"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
```

```rust
#[tokio::test]
async fn test_list() -> Result<()> {
    let test_zip = concat!(env!("CARGO_MANIFEST_DIR"), "/test_resources/test.zip");
    let zip_file = File::open(test_zip).await?;
    let content = compress_tools::tokio_support::list_archive_files(zip_file).await?;
    println!("content={:?}", content);
    Ok(())
}
```

Environment:
* OS: macOS 13.1
* libarchive: 3.6.2 (installed from brew)

Any help is appreciated
